handle_api_time_sync - error
When ntp daemon is installed and running ntpdate invocation returns error.

Error:  ntpdate[12919]: the NTP socket is in use, exiting

Need to use ntpdate with -u switch to be on the safe side. In this case ntpdate uses unprivileged random port for outgoing packets.